### ISSUE TITLE
Open Terminal path should be quoted

### ISSUE THREAD

**Issue by effervescent** [jmjeong/alfred-extension#2]
https://github.com/jmjeong/alfred-extension/blob/master/managealfredextension/info.plist#L103

You should have double quotes around {query} so that spaces in the file path are interpreted correctly.
Also, the command opened 2 terminal windows for me, so I think you only need to change directories, since a new terminal window is spawned for you already.

change:

open -a Terminal {query}
to
cd "{query}"

Thanks for the workflow!

**Comment by jmjeong** [comment]
thank you.

I will change it in the next release.

2015-04-14 5:37 GMT+09:00 Mark <notifications@github.com>:

>
> https://github.com/jmjeong/alfred-extension/blob/master/managealfredextension/info.plist#L103
>
> You should have double quotes around {query} so that spaces in the file
> path are interpreted correctly.
>
> open -a Terminal "{query}"
>
> Thanks for the workflow!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jmjeong/alfred-extension/issues/2>.
>



-- 
Jaemok Jeong
