### ISSUE TITLE
Alfred 3 compatibility

### ISSUE THREAD

**Issue by mystygage** [jmjeong/alfred-extension#5]
I use your Pinboard workflow and recently upgraded to Alfred 3.
Some actions like pbreload use a osascript with a hardcoded string `Alfred 2`:
```
tell application "Alfred 2" to run trigger "reload" in workflow "com.jmjeong.alfredv2.pinboard" with argument "test"
return "Reloading... Please wait."
```
I manually changed this to `Alfred 3` and reload started working again.

There are some other strings like in this identifier, which were already changed to `Alfred 3`. So I'm not totally sure if this is an extension problem or sth. which should be handled during upgrade from Alfred 2 to Alfred 3.

![screen shot 2016-05-19 at 16 38 27](https://cloud.githubusercontent.com/assets/1107406/15397368/4a321696-1de0-11e6-8029-7ffdfb4c707a.png)

**Comment by jmjeong-nemus** [comment]
Thank you for reporting.

Updated alfred-pinboard into v2.3 which supports alfred v3.

**Comment by mystygage** [comment]
Thanks!
