### ISSUE TITLE
How to open alfred extensions in iTerm instead of Terminal?

### ISSUE THREAD

**Issue by nikitavoloboev** [jmjeong/alfred-extension#6]
I thought that changing this : 

![2016-05-21 at 11 59](https://cloud.githubusercontent.com/assets/6391776/15447717/8dd37c2a-1f4b-11e6-9966-f1b0eaf36485.png)

for this : 

![2016-05-21 at 12 00](https://cloud.githubusercontent.com/assets/6391776/15447723/a5a636b2-1f4b-11e6-8e2f-fffde1ec3712.png)

Would work but it doesn't. Do you know what I should change to make it work?

Thank you.

**Comment by jmjeong** [comment]
What if user doesn't install iTeam?

**Comment by nikitavoloboev** [comment]
I understand. That's why it is set to terminal as default there. But I want to change it to iTerm and I was wondering how I could do it. I would think that open -a iTerm would work but it doesn't.

**Comment by jmjeong** [comment]
Update managealfredextension workflow to v2.11

- alfred 3 support
- use iTerm 2 as default terminal (actually, I use iTerm 2, too)

**Comment by nikitavoloboev** [comment]
Thank you for adding the support for it however I downloaded it and it still doesn't work for me. I made a screencast too : http://quick.as/kr01H5x3q

Perhaps I am doing something wrong.

**Comment by jmjeong-nemus** [comment]
I made animaged gif. 

http://www.giphy.com/gifs/3oEjI3RA5QNXundm4E

**Comment by nikitavoloboev** [comment]
Hey Jaemok,

The issue still persists with me and I cannot get it to show in iTerm. It's really strange that it works for you and doesn't for me. I have tested it multiple times with multiple windows, do you know what might be causing this issue?

Thank you.

**Comment by jmjeong** [comment]
What kind of iTerm version do you use? The recent iTerm changes applescript APIs.

**Comment by nikitavoloboev** [comment]
3.0.4 is the version I am running.

![2016-07-09 at 10 07](https://cloud.githubusercontent.com/assets/6391776/16706862/fc211e98-45bc-11e6-82b7-976e50259dde.png)

**Comment by jmjeong** [comment]
I just released new version. How about checking it?

**Comment by nikitavoloboev** [comment]
This works now, thank you.

However do you know how I can make it open in my current profile in iTerm?

I switch focus to iTerm with a hotkey, I have it set in preferences  : 

![2016-07-10 at 12 59](https://cloud.githubusercontent.com/assets/6391776/16713141/33e63ba6-469e-11e6-9586-8cb641f7bcf7.png)

Perhaps you can test it too, would it be possible you think to have it open in there rather creating a new window every time? I hope you can understand what I mean. Thank you.

**Comment by nikitavoloboev** [comment]
Hey,

I am still struggling to make it work. Perhaps you can help me. I would really appreciate it.

**Comment by nikitavoloboev** [comment]
All right, I have solved it with this code : 

`
-- This is v0.6 of the custom script for AlfredApp for iTerm 2.9+
-- Please see https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/
-- for the latest changes.

-- Please note, if you store the iTerm binary in any other location than the Applications Folder
-- please ensure you update the two locations below (in the format of : rather than / for folder dividers)
-- this gets around issues with AppleScript not handling things well if you have two iTerm binaries on your system... which can happen :D

on alfred_script(q)
	if application "iTerm2" is running or application "iTerm" is running then
		run script "
			on run {q}
				tell application \":Applications:iTerm.app\"
					activate
					try
						select first window
						set onlywindow to false
					on error
						create window with default profile
						select first window
						set onlywindow to true
					end try
					tell the first window
						if onlywindow is false then
							create tab with default profile
						end if
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	else
		run script "
			on run {q}
				tell application \":Applications:iTerm.app\"
					activate
					try
						select first window
					on error
						create window with default profile
						select first window
					end try
					tell the first window
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	end if
end alfred_script
`

**Comment by jmjeong** [comment]
Thank you for the information. I just released the workflow v2.12 which adds your code.
