### ISSUE TITLE
My alfred preferences like in ~/Documents/d. app/alfred and workflow doesn't open the files

### ISSUE THREAD

**Issue by nikitavoloboev** [jmjeong/alfred-extension#7]
When I try to run the workflow to find and open the workflow directory, I get this every time : 

![2016-10-11 at 20 57](https://cloud.githubusercontent.com/assets/6391776/19284244/6364ee36-8ff5-11e6-8658-d66925fe4ede.png)

What should I modify in the script to make it work for this path? 

Thank you for any help.

**Comment by jmjeong-nemus** [comment]
What kind of alfred-extension do you use? I will investigate it.

**Comment by nikitavoloboev** [comment]
This is no longer a problem. Thank you for the help though.
